name: setup-node
description: 'Set up Node.js'
runs:
    using: 'composite'
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
              node-version: 20
        - name: Cache dependencies
          id: cache_dependencies
          uses: actions/cache@v3
          with:
            path: node_modules
            key: node-modules-${{ hashFiles('**/package-lock.json') }}
        - name: Install dependencies
          shell: bash
          if: steps.cache_dependencies.outputs.cache-hit != 'true'
          run: npm ci