name: setup-node
description: 'Set up Node.js'
runs:
    using: 'composite'
    steps:
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
              node-version: 20
        - name: Cache dependencies
          id: cache_dependencies
          uses: actions/cache@v4
          with:
            path: |
              ~/.npm
              ${{ github.workspace }}/.next/cache
            key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
            restore-keys: |
              ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
        - name: Install dependencies
          shell: bash
          if: steps.cache_dependencies.outputs.cache-hit != 'true'
          run: |
            cd portfolio-akemi
            npm ci